import {
  WaxType,
  ContainerType,
  CandleSize,
  WickType,
  ScentOption,
  StandardProduct,
  LagosDeliveryArea
} from './types';

export const WAX_TYPES: WaxType[] = [
  {
    id: 'soy',
    name: 'Pure Soy Wax',
    description: '100% organic soybean wax. Clean-burning, biodegradable, and throws scent beautifully.',
    priceNgn: 4500,
  },
  {
    id: 'coconut',
    name: 'Creamy Coconut Wax',
    description: 'Premium slow-burning wax. Rich, luxurious burn with an extremely smooth finish.',
    priceNgn: 6000,
  },
  {
    id: 'beeswax',
    name: 'Natural Beeswax',
    description: 'Golden, therapeutic, and hypoallergenic wax. Emits a subtle natural honey aroma.',
    priceNgn: 7500,
  },
];

export const CONTAINER_TYPES: ContainerType[] = [
  {
    id: 'amber',
    name: 'Amber Glass Jar',
    description: 'Warm, vintage aesthetic. Projects a beautiful golden, comforting glow when lit.',
    priceNgn: 2500,
    image: '/src/assets/images/amber_candle_lumina_1783901509982.jpg',
    colorClass: 'bg-amber-800 border-amber-950',
  },
  {
    id: 'black',
    name: 'Matte Black Ceramic',
    description: 'Sleek, modern, and moody. A highly sophisticated addition to any minimal space.',
    priceNgn: 3500,
    image: '/src/assets/images/black_candle_lumina_1783901521061.jpg',
    colorClass: 'bg-zinc-900 border-zinc-950',
  },
  {
    id: 'ceramic',
    name: 'Artisanal Ceramic Bowl',
    description: 'Individually handcrafted neutral clay. Earthy, textured, and perfect for multi-wick setups.',
    priceNgn: 5000,
    image: '/src/assets/images/ceramic_candle_lumina_1783901530348.jpg',
    colorClass: 'bg-stone-300 border-stone-400',
  },
  {
    id: 'crystal',
    name: 'Faceted Clear Crystal',
    description: 'Opulent and dazzling. Refracts the flame into dancing, kaleidoscopic rays.',
    priceNgn: 6500,
    image: '/src/assets/images/crystal_candle_lumina_1783901540612.jpg',
    colorClass: 'bg-slate-100 border-slate-200 backdrop-blur-xs',
  },
];

export const CANDLE_SIZES: CandleSize[] = [
  {
    id: '4oz',
    name: 'Petite 4oz (120ml)',
    description: 'Perfect for testing scents or small spaces. ~25 hours burn time.',
    priceNgn: 2000,
  },
  {
    id: '8oz',
    name: 'Signature 8oz (240ml)',
    description: 'Our most popular size. Rich scent throw for medium rooms. ~50 hours burn time.',
    priceNgn: 4000,
  },
  {
    id: '12oz',
    name: 'Grande 12oz (360ml)',
    description: 'Luxury heavy pour. Best for large living spaces. ~75 hours burn time.',
    priceNgn: 6500,
  },
];

export const WICK_TYPES: WickType[] = [
  {
    id: 'cotton',
    name: 'Organic Cotton Wick',
    description: 'Lead-free, woven cotton. Consistent, reliable, and provides a silent steady flame.',
    priceNgn: 500,
  },
  {
    id: 'wood',
    name: 'Crackling Wood Wick',
    description: 'Eco-friendly wooden slab. Emits a cozy, relaxing crackling sound like a tiny fireplace.',
    priceNgn: 1500,
  },
];

export const SCENT_OPTIONS: ScentOption[] = [
  {
    id: 'lavender',
    name: 'Provincial Lavender',
    description: 'Calming French lavender fields, promoting deep relaxation and restful sleep.',
    notes: 'Herbaceous, floral, soothing',
    category: 'Floral',
    color: 'from-purple-300 to-purple-400',
  },
  {
    id: 'vanilla',
    name: 'Warm Madagascar Vanilla',
    description: 'Decadent, sweet, and comforting vanilla bean extract with a hint of spun sugar.',
    notes: 'Sweet, creamy, nostalgic',
    category: 'Sweet & Warm',
    color: 'from-amber-200 to-amber-300',
  },
  {
    id: 'sandalwood',
    name: 'Creamy Sandalwood & Amber',
    description: 'An earth-rich, grounding scent that adds a sensual and sophisticated warmth to any room.',
    notes: 'Woody, rich, velvety',
    category: 'Woody',
    color: 'from-amber-600 to-amber-700',
  },
  {
    id: 'jasmine',
    name: 'Midnight Bloom Jasmine',
    description: 'Exotic jasmine blossoms picked at midnight for their most potent, seductive aroma.',
    notes: 'Exotic floral, sweet, fresh',
    category: 'Floral',
    color: 'from-pink-100 to-pink-200',
  },
  {
    id: 'eucalyptus',
    name: 'Eucalyptus & Nigerian Mint',
    description: 'Cooling, crisp, and clarifying. Perfect for mental focus, sinus relief, and spa vibes.',
    notes: 'Fresh, herbal, cooling',
    category: 'Fresh & Herbal',
    color: 'from-emerald-300 to-emerald-400',
  },
  {
    id: 'citrus',
    name: 'Sun-Kissed Orange Blossom',
    description: 'Bright citrus orchards and sweet orange blossoms that lift spirits and energize spaces.',
    notes: 'Zesty, bright, floral',
    category: 'Fresh & Herbal',
    color: 'from-orange-300 to-orange-400',
  },
  {
    id: 'cinnamon_ginger',
    name: 'Lagos Ginger & Cinnamon Spice',
    description: 'A luxurious Nigerian ginger and spicy cinnamon blend, invoking warmth and vibrant life.',
    notes: 'Warm spice, zesty ginger, rich',
    category: 'Spicy',
    color: 'from-red-600 to-red-700',
  },
  {
    id: 'cocoa_orchid',
    name: 'Gbagada Cocoa & Wild Orchid',
    description: 'Earthy premium roasted cocoa beans elegantly matched with exotic purple orchids.',
    notes: 'Dark chocolate, sweet floral, rich',
    category: 'Sweet & Warm',
    color: 'from-rose-800 to-rose-900',
  },
  {
    id: 'lekki_breeze',
    name: 'Lekki Coconut Breeze',
    description: 'Sun-drenched cream of coconut combined with mineral sea salt and crisp lemongrass, evoking the refreshing sea spray of Lekki beaches.',
    notes: 'Tropical coconut, mineral sea salt, lemongrass',
    category: 'Fresh & Herbal',
    color: 'from-sky-300 to-cyan-400',
  },
  {
    id: 'ikeja_oud',
    name: 'Ikeja Sweet Oud & Amber',
    description: 'A rich, complex, and calming agarwood combined with velvety warm amber, designed to melt away the stress of mainland rush hours.',
    notes: 'Exotic oud, woody amber, sweet balsamic',
    category: 'Woody',
    color: 'from-yellow-700 to-amber-900',
  },
  {
    id: 'lasgidi_chai',
    name: 'Lasgidi Chai & Pepperfruit',
    description: 'A vibrant blend of indigenous spicy West African pepperfruit, warming black tea, and crushed cardamoms.',
    notes: 'Indigenous pepperfruit, black tea, zesty clove',
    category: 'Spicy',
    color: 'from-orange-600 to-red-800',
  },
];

export const STANDARD_PRODUCTS: StandardProduct[] = [
  {
    id: 'eko-sunset',
    name: 'Eko Sunset',
    description: 'A brilliant, warm scent inspired by the glowing Lagos horizon. Combines rich Lagos ginger, premium cinnamon spice, and sweet Madagascar vanilla to evoke an energizing warmth.',
    priceNgn: 11000,
    container: 'amber',
    size: '8oz',
    wick: 'wood',
    scents: ['cinnamon_ginger', 'vanilla'],
    image: '/src/assets/images/amber_candle_lumina_1783901509982.jpg',
    tag: 'Bestseller',
    rating: 4.9,
  },
  {
    id: 'lekki-breeze',
    name: 'Lekki Coconut Breeze',
    description: 'Evoke the laid-back elegance of Lekki beaches. Pure organic coconut wax infused with sun-drenched cream of coconut, mineral sea salt, and a refreshing burst of zesty orange blossoms.',
    priceNgn: 14500,
    container: 'crystal',
    size: '8oz',
    wick: 'cotton',
    scents: ['lekki_breeze', 'citrus'],
    image: '/src/assets/images/crystal_candle_lumina_1783901540612.jpg',
    tag: 'Beachside Luxury',
    rating: 4.9,
  },
  {
    id: 'gbagada-breeze',
    name: 'Gbagada Breeze',
    description: 'Crafted right here in Gbagada. A purifying blend of herbal eucalyptus and fresh Nigerian mint, grounding into a rich undertone of creamy sandalwood to clear your space and mind.',
    priceNgn: 13500,
    container: 'black',
    size: '8oz',
    wick: 'wood',
    scents: ['eucalyptus', 'sandalwood'],
    image: '/src/assets/images/black_candle_lumina_1783901521061.jpg',
    tag: 'Local Favorite',
    rating: 4.8,
  },
  {
    id: 'ikeja-oud',
    name: 'Ikeja Amber Oud',
    description: 'Ground yourself after a long mainland commute. A highly sophisticated blend of premium dark agarwood (oud), smoky sandalwood, and warm Madagascar vanilla with a cozy, crackling wood wick.',
    priceNgn: 16500,
    container: 'black',
    size: '8oz',
    wick: 'wood',
    scents: ['ikeja_oud', 'vanilla'],
    image: '/src/assets/images/ikeja_amber_oud_candle_1783901721118.jpg',
    tag: 'Warm & Woody',
    rating: 5.0,
  },
  {
    id: 'island-luxe',
    name: 'Island Luxe',
    description: 'Inspired by the opulent beachside villas of Victoria Island and Lekki. A decadent scent pairing midnight bloom jasmine with sweet orange blossoms, refracting gorgeous floral energy.',
    priceNgn: 18000,
    container: 'crystal',
    size: '12oz',
    wick: 'cotton',
    scents: ['jasmine', 'citrus'],
    image: '/src/assets/images/crystal_candle_lumina_1783901540612.jpg',
    tag: 'Luxury',
    rating: 5.0,
  },
  {
    id: 'isale-eko-gold',
    name: 'Isale Eko Gold',
    description: 'A celebration of rich Lagos traditions. Combines zesty Lagos ginger, premium roasted cocoa bean extract, wild orchids, and vanilla. Poured in a massive, textured 12oz ceramic bowl for a dramatic 75hr burn.',
    priceNgn: 24000,
    container: 'ceramic',
    size: '12oz',
    wick: 'wood',
    scents: ['cinnamon_ginger', 'cocoa_orchid', 'vanilla'],
    image: '/src/assets/images/isale_eko_gold_1783902493475.jpg',
    tag: 'Heritage Edition',
    rating: 4.9,
  },
  {
    id: 'mainland-warmth',
    name: 'Mainland Warmth',
    description: 'A cozy double-wick pottery masterpiece. Grounding provincial lavender is matched perfectly with earthy dark cocoa and sweet orchid to form a relaxing evening escape.',
    priceNgn: 21500,
    container: 'ceramic',
    size: '12oz',
    wick: 'cotton',
    scents: ['lavender', 'cocoa_orchid'],
    image: '/src/assets/images/mainland_warmth_1783902509311.jpg',
    tag: 'Limited Edition',
    rating: 4.7,
  },
];

export const LAGOS_DELIVERY_AREAS: LagosDeliveryArea[] = [
  { id: 'gbagada-pickup', name: 'Gbagada Office (Free Pickup)', feeNgn: 0, time: 'Ready in 24 hours' },
  { id: 'gbagada-del', name: 'Gbagada Local Delivery', feeNgn: 1500, time: 'Same-day or next-day delivery' },
  { id: 'mainland', name: 'Lagos Mainland (Yaba, Maryland, Surulere, Ikeja, etc.)', feeNgn: 2500, time: '1 - 2 business days' },
  { id: 'island', name: 'Lagos Island (Lekki, Victoria Island, Ikoyi)', feeNgn: 3500, time: '1 - 2 business days' },
  { id: 'outer-lagos', name: 'Outer Lagos (Ajah, Festac, Abule Egba, Sangotedo)', feeNgn: 4500, time: '2 - 3 business days' },
  { id: 'interstate', name: 'Interstate (Outside Lagos)', feeNgn: 6500, time: '3 - 5 business days' },
];

export const WHATSAPP_VENDOR_NUMBER = '2348164701851'; // Updated as requested by customer.
